# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build_deploy:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6.5-buster-node-browsers-legacy

    working_directory: ~/repo

    steps:
      - checkout
      - run: './.circleci/build.sh'
      - run: './.circleci/deploy.sh'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_deploy
